<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCdOiuVB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCdOiuVB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCdOiuVB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCdOiuVB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCdOiuVB\App_KernelDevDebugContainer([
    'container.build_hash' => 'CdOiuVB',
    'container.build_id' => 'd2d57325',
    'container.build_time' => 1654207580,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCdOiuVB');
