<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLAn8bt4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLAn8bt4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLAn8bt4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLAn8bt4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLAn8bt4\App_KernelDevDebugContainer([
    'container.build_hash' => 'LAn8bt4',
    'container.build_id' => '6357e0fd',
    'container.build_time' => 1654197364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLAn8bt4');
